### ISSUE TITLE
New Feature Proposal: Support for TOML Configuration Files

### ISSUE THREAD

**Issue by mnajibi** [sdthaker/Node-TILify#12]
Hi @sdthaker  , I would like to work on your repo to implement a new feature. This feature would allow users to make changes to the program's settings using a special file. Instead of typing out all the settings every time they use the program, users could save their choices in a file named something like "config.toml.

**Comment by sdthaker** [comment]
Sure please go ahead and create a PR when ready, will get it merged post review phase. Thanks! @mnajibi
