### ISSUE TITLE
Missing feature: users have the option to provide a stylesheet URL

### ISSUE THREAD

**Issue by avelynhc** [sdthaker/Node-TILify#2]
- Expected to allow users to optionally specify a stylesheet URL with --stylesheet or -s, but default CSS stylesheet to be used.
- There is no feature for the user to specify the URL themselves.

**Comment by sdthaker** [comment]
The stylesheet feature is an optional feature. Since I've already implemented 3 optional features, (a minimum of 2 asked to be implemented), I won't be implementing this feature.
