### ISSUE TITLE
Upate README.md

### ISSUE THREAD

**Issue by avelynhc** [sdthaker/Node-TILify#3]
- Once you update the code to allow users to specify the CSS stylesheet URL, it would be better to provide more information about this by including usages/examples.
- It can be beneficial for users if you include a few screenshots of usage with real output in the README.md. This will help users gain a better understanding of what this app does at a higher level.

**Comment by sdthaker** [comment]
Bullet point 1 is already covered in [another issue](https://github.com/sdthaker/Node-TILify/issues/2)

**Comment by sdthaker** [comment]
Bullet point 2 was fixed in this commit -> [d46514](https://github.com/sdthaker/Node-TILify/commit/d4651485f1e6e319fa72e364609d7122eef6db46)
