### ISSUE TITLE
Extract filename with basename() method

### ISSUE THREAD

**Issue by avelynhc** [sdthaker/Node-TILify#5]
When you need to extract only the filename from the file path, you can use the [basename()](https://nodejs.org/api/path.html#pathbasenamepath-suffix) method. This function returns only the filename, so you don't need to use split in this case.

Instead of using `split()` in line 138-139 helper.js
```javascript
    let inputFileArr = inputFile.split('/');
    fileName = inputFileArr[inputFileArr.length - 1].split('.')[0];
```

Use `path.basename()`
```javascript
import path from "path";
fileName = path.basename(inputFile, '.txt');
```

**Comment by sdthaker** [comment]
This issue is now fixed: [472d27e](https://github.com/sdthaker/Node-TILify/commit/472d27e6390c7786f8f91967e855a154885be6fb)
