### ISSUE TITLE
Windows issue related to pathname

### ISSUE THREAD

**Issue by bhavik001** [sdthaker/Node-TILify#7]
Getting an issue while cloning the git repo to my windows computer.
Windows doesn’t accept "?" as name of the path or filename.
The error it shows is:
error: invalid path 'examples/What do API Keys REALLY do?.txt'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by sdthaker** [comment]
Issue fixed in this commit -> [df2c7c](https://github.com/sdthaker/Node-TILify/commit/df2c7cf92674be917c8920cdf779e46d92e964fa)
